set(BUILDINFO_H ${CMAKE_BINARY_DIR}/include/buildinfo.h)
string(TIMESTAMP CURRENT_TIMESTAMP)
file(WRITE ${BUILDINFO_H}
     "/* This file is auto-generated by CMake on ${CURRENT_TIMESTAMP}. */\n\n")
file(APPEND ${BUILDINFO_H} "#ifndef RTORRENT_BUILDINFO_H\n")
file(APPEND ${BUILDINFO_H} "#define RTORRENT_BUILDINFO_H\n\n")

file(APPEND ${BUILDINFO_H} "/* Version number of package */\n")
file(APPEND ${BUILDINFO_H} "#define RT_VERSION \"${PROJECT_VERSION}\"\n\n")

file(APPEND ${BUILDINFO_H} "/* Version number of API */\n")
file(APPEND ${BUILDINFO_H} "#define RT_API_VERSION \"${API_VERSION}\"\n\n")

file(APPEND ${BUILDINFO_H} "/* Http user agent */\n")
file(
  APPEND ${BUILDINFO_H}
  "#define RT_USER_AGENT std::string(\"${PROJECT_NAME}\" \"/\" RT_VERSION \"/\") + torrent::version()\n\n"
)

if(USE_EXTRA_DEBUG)
  file(APPEND ${BUILDINFO_H} "/* Enable extra debugging checks */\n")
  file(APPEND ${BUILDINFO_H} "#define RT_USE_EXTRA_DEBUG 1\n\n")
endif()

if(USE_XMLRPC)
  file(APPEND ${BUILDINFO_H} "/* Support for XMLRPC-C */\n")
  file(APPEND ${BUILDINFO_H} "#define HAVE_XMLRPC_C 1\n\n")
endif()

if(CURSES_FOUND)
  if(CURSES_NEED_WIDE)
    if(CURSES_HAVE_NCURSES_CURSES_H)
      file(APPEND ${BUILDINFO_H} "/* <ncursesw/curses.h> */\n")
      file(APPEND ${BUILDINFO_H} "#define HAVE_NCURSESW_CURSES_H 1\n\n")
    elseif(CURSES_HAVE_NCURSES_H)
      file(APPEND ${BUILDINFO_H} "/* <ncursesw.h> */\n")
      file(APPEND ${BUILDINFO_H} "#define HAVE_NCURSESW_H 1\n\n")
    endif()
  else()
    if(CURSES_HAVE_NCURSES_CURSES_H)
      file(APPEND ${BUILDINFO_H} "/* <ncurses/curses.h> */\n")
      file(APPEND ${BUILDINFO_H} "#define HAVE_NCURSES_CURSES_H 1\n\n")
    elseif(CURSES_HAVE_NCURSES_H)
      file(APPEND ${BUILDINFO_H} "/* <ncurses.h> */\n")
      file(APPEND ${BUILDINFO_H} "#define HAVE_NCURSES_H 1\n\n")
    else()
      file(APPEND ${BUILDINFO_H} "/* <curses.h> */\n")
      file(APPEND ${BUILDINFO_H} "#define HAVE_CURSES_H 1\n\n")
    endif()
  endif()
endif()

file(APPEND ${BUILDINFO_H} "#endif\n")
