set(BUILDINFO_H ${CMAKE_BINARY_DIR}/include/buildinfo.h)
string(TIMESTAMP CURRENT_TIMESTAMP)
file(WRITE ${BUILDINFO_H}
     "/* This file is auto-generated by CMake on ${CURRENT_TIMESTAMP}. */\n\n")
file(APPEND ${BUILDINFO_H} "#ifndef RTORRENT_BUILDINFO_H\n")
file(APPEND ${BUILDINFO_H} "#define RTORRENT_BUILDINFO_H\n\n")

file(APPEND ${BUILDINFO_H} "/* Version number of package */\n")
file(APPEND ${BUILDINFO_H} "#define RT_VERSION \"${PROJECT_VERSION}\"\n\n")

file(APPEND ${BUILDINFO_H} "/* Version number of API */\n")
file(APPEND ${BUILDINFO_H} "#define RT_API_VERSION \"${API_VERSION}\"\n\n")

file(APPEND ${BUILDINFO_H} "/* Http user agent */\n")
file(
  APPEND ${BUILDINFO_H}
  "#define RT_USER_AGENT std::string(\"${PROJECT_NAME}\" \"/\" RT_VERSION \"/\") + torrent::version()\n\n"
)

if(USE_EXTRA_DEBUG)
  file(APPEND ${BUILDINFO_H} "/* Enable extra debugging checks */\n")
  file(APPEND ${BUILDINFO_H} "#define RT_USE_EXTRA_DEBUG 1\n\n")
endif()

if(USE_RUNTIME_CA_DETECTION)
  file(APPEND ${BUILDINFO_H} "/* Runtime detection of path to CA bundle */\n")
  file(APPEND ${BUILDINFO_H} "#define RT_USE_RUNTIME_CA_DETECTION 1\n\n")
endif()

if(USE_XMLRPC)
  file(APPEND ${BUILDINFO_H} "/* Support for XMLRPC-C */\n")
  file(APPEND ${BUILDINFO_H} "#define HAVE_XMLRPC_C 1\n\n")
endif()

file(APPEND ${BUILDINFO_H} "#endif\n")
